// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvlqxbcpijjdpehtiayh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bHF4YmNwaWpqZHBlaHRpYXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjU2NjUsImV4cCI6MjA2ODE0MTY2NX0.V1tFv4j0YsUDQjileRPuYsBSsU34iLVLWzaFl1ZC7zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});